version: '3.5'
services:
  restful-modbus-api:
    image: restful-modbus-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restful-modbus-api
    ports:
      - 5000:5000
    volumes:
      - .:/root
    command: |
      -a 0.0.0.0 -p 5000 -t tests/sample_template.yml

  dummy-modbus-server:
    image: dummy-modbus-server:latest
    build:
      context: .
      dockerfile: dummy-modbus-server/Dockerfile
    container_name: dummy-modbus-server
    ports:
      - 502:502
    command: |
      -a 0.0.0.0 -p 502

  dummy-modbus-rtu-over-tcp-server:
    image: dummy-modbus-rtu-over-tcp-server:latest
    build:
      context: .
      dockerfile: dummy-modbus-rtu-over-tcp-server/Dockerfile
    container_name: dummy-modbus-rtu-over-tcp-server
    ports:
      - 1502:502
    command: |
      -a 0.0.0.0 -p 502
